/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './node.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from 'angular2-platform-node/node-platform';
import * as import5 from 'angular2-platform-node/node-http';
import * as import6 from 'angular2-universal/node/universal-module';
import * as import7 from '@angular/forms/src/directives';
import * as import8 from '@angular/forms/src/form_providers';
import * as import9 from '@angular/router/src/router_module';
import * as import10 from './+app/shared/shared.module';
import * as import11 from './+app/+home/home-routing.module';
import * as import12 from './+app/+home/home.module';
import * as import13 from './+app/+about/about-routing.module';
import * as import14 from './+app/+about/about.module';
import * as import15 from './+app/+todo/todo-routing.module';
import * as import16 from './+app/+todo/todo.module';
import * as import17 from './+app/app-routing.module';
import * as import18 from './+app/app.module';
import * as import19 from './+app/shared/cache.service';
import * as import20 from '@angular/common/src/localization';
import * as import21 from '@angular/core/src/application_init';
import * as import22 from '@angular/core/src/testability/testability';
import * as import23 from '@angular/core/src/application_ref';
import * as import24 from '@angular/core/src/linker/compiler';
import * as import25 from 'angular2-platform-node/node-shared-styles-host';
import * as import26 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import27 from 'angular2-platform-node/node-renderer';
import * as import28 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import29 from '@angular/core/src/linker/view_utils';
import * as import30 from 'angular2-platform-node/node-location';
import * as import31 from '@angular/http/src/base_request_options';
import * as import32 from '@angular/http/src/base_response_options';
import * as import33 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import34 from '@angular/forms/src/form_builder';
import * as import35 from '@angular/common/src/location/location';
import * as import36 from '@angular/router/src/url_tree';
import * as import37 from '@angular/router/src/router_outlet_map';
import * as import38 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import39 from '@angular/router/src/router_preloader';
import * as import40 from './+app/shared/api.service';
import * as import41 from './+app/shared/model/model.service';
import * as import42 from './angular2-meta';
import * as import43 from '@angular/core/src/di/injector';
import * as import44 from './+app/+home/home.component.ngfactory';
import * as import45 from './+app/+about/about.component.ngfactory';
import * as import46 from './+app/+todo/todo.component.ngfactory';
import * as import47 from './+app/app.component.ngfactory';
import * as import48 from '@angular/core/src/zone/ng_zone';
import * as import49 from '@angular/platform-browser/src/dom/events/key_events';
import * as import50 from './+app/+home/home.component';
import * as import51 from './+app/+about/about.component';
import * as import52 from './+app/+todo/todo.component';
import * as import53 from 'angular2-universal/node/env';
import * as import54 from '@angular/router/src/router';
import * as import55 from '@angular/core/src/console';
import * as import56 from '@angular/core/src/i18n/tokens';
import * as import57 from '@angular/core/src/error_handler';
import * as import58 from '@angular/core/src/application_tokens';
import * as import59 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import60 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import61 from '@angular/platform-browser/src/dom/animation_driver';
import * as import62 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import63 from '@angular/core/src/render/api';
import * as import64 from '@angular/core/src/security';
import * as import65 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import66 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import67 from 'angular2-platform-node/tokens';
import * as import68 from '@angular/common/src/location/location_strategy';
import * as import69 from '@angular/common/src/location/platform_location';
import * as import70 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import71 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import72 from '@angular/http/src/interfaces';
import * as import73 from '@angular/http/src/backends/browser_xhr';
import * as import74 from '@angular/http/src/backends/xhr_backend';
import * as import75 from '@angular/http/src/http';
import * as import76 from '@angular/http/src/backends/jsonp_backend';
import * as import77 from '@angular/router/src/router_config_loader';
import * as import78 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import79 from '@angular/router/src/router_state';
class MainModuleInjector extends import0.NgModuleInjector<import1.MainModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _NodeModule_2:import4.NodeModule;
  _NodeHttpModule_3:import5.NodeHttpModule;
  _NodeJsonpModule_4:import5.NodeJsonpModule;
  _UniversalModule_5:import6.UniversalModule;
  _InternalFormsSharedModule_6:import7.InternalFormsSharedModule;
  _FormsModule_7:import8.FormsModule;
  _ROUTER_FORROOT_GUARD_8:any;
  _RouterModule_9:import9.RouterModule;
  _ReactiveFormsModule_10:import8.ReactiveFormsModule;
  _SharedModule_11:import10.SharedModule;
  _HomeRoutingModule_12:import11.HomeRoutingModule;
  _HomeModule_13:import12.HomeModule;
  _AboutRoutingModule_14:import13.AboutRoutingModule;
  _AboutModule_15:import14.AboutModule;
  _TodoRoutingModule_16:import15.TodoRoutingModule;
  _TodoModule_17:import16.TodoModule;
  _AppRoutingModule_18:import17.AppRoutingModule;
  _AppModule_19:import18.AppModule;
  _LRU_20:any;
  _CacheService_21:import19.CacheService;
  _MainModule_22:import1.MainModule;
  __LOCALE_ID_23:any;
  __NgLocalization_24:import20.NgLocaleLocalization;
  _ErrorHandler_25:any;
  _ApplicationInitStatus_26:import21.ApplicationInitStatus;
  _TestabilityRegistry_27:import4.MockTestabilityRegistry;
  _Testability_28:import22.Testability;
  _ApplicationRef__29:import23.ApplicationRef_;
  __ApplicationRef_30:any;
  __Compiler_31:import24.Compiler;
  __APP_ID_32:any;
  __NodeSharedStylesHost_33:import25.NodeSharedStylesHost;
  __DOCUMENT_34:any;
  __NodeDomEventsPlugin_35:import4.NodeDomEventsPlugin;
  __HAMMER_GESTURE_CONFIG_36:import26.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_37:any[];
  __NodeEventManager_38:import4.NodeEventManager;
  __EventManager_39:any;
  __AnimationDriver_40:any;
  __NodeDomRootRenderer_41:import27.NodeDomRootRenderer;
  __DomRootRenderer_42:any;
  __RootRenderer_43:any;
  __DomSanitizer_44:import28.DomSanitizerImpl;
  __Sanitizer_45:any;
  __ViewUtils_46:import29.ViewUtils;
  __IterableDiffers_47:any;
  __KeyValueDiffers_48:any;
  __ORIGIN_URL_49:any;
  __REQUEST_URL_50:any;
  __APP_BASE_HREF_51:any;
  __PlatformLocation_52:import30.NodePlatformLocation;
  __DomEventsPlugin_53:any[];
  __SharedStylesHost_54:any;
  __DomSharedStylesHost_55:any;
  __XSRFStrategy_56:any;
  __BrowserXhr_57:any;
  __RequestOptions_58:import31.BaseRequestOptions;
  __ResponseOptions_59:import32.BaseResponseOptions;
  __XHRBackend_60:import5.NodeBackend;
  __Http_61:any;
  __JSONPBackend_62:import5.NodeJsonpBackend_;
  __Jsonp_63:any;
  __RadioControlRegistry_64:import33.RadioControlRegistry;
  __FormBuilder_65:import34.FormBuilder;
  __ROUTES_66:any[];
  __ROUTER_CONFIGURATION_67:any;
  __LocationStrategy_68:any;
  __Location_69:import35.Location;
  __UrlSerializer_70:import36.DefaultUrlSerializer;
  __RouterOutletMap_71:import37.RouterOutletMap;
  __NgModuleFactoryLoader_72:import38.SystemJsNgModuleLoader;
  __Router_73:any;
  __ActivatedRoute_74:any;
  _NoPreloading_75:import39.NoPreloading;
  _PreloadingStrategy_76:any;
  _RouterPreloader_77:import39.RouterPreloader;
  __PreloadAllModules_78:import39.PreloadAllModules;
  __APP_BOOTSTRAP_LISTENER_79:any[];
  __ApiService_80:import40.ApiService;
  __ModelService_81:import41.ModelService;
  __isBrowser_82:any;
  __isNode_83:any;
  __req_84:any;
  __res_85:any;
  __Meta_86:import42.Meta;
  constructor(parent:import43.Injector) {
    super(parent,[
      import44.HomeComponentNgFactory,
      import45.AboutComponentNgFactory,
      import46.TodoComponentNgFactory,
      import47.AppComponentNgFactory
    ]
    ,[import47.AppComponentNgFactory]);
  }
  get _LOCALE_ID_23():any {
    if ((this.__LOCALE_ID_23 == (null as any))) { (this.__LOCALE_ID_23 = 'en-US'); }
    return this.__LOCALE_ID_23;
  }
  get _NgLocalization_24():import20.NgLocaleLocalization {
    if ((this.__NgLocalization_24 == (null as any))) { (this.__NgLocalization_24 = new import20.NgLocaleLocalization(this._LOCALE_ID_23)); }
    return this.__NgLocalization_24;
  }
  get _ApplicationRef_30():any {
    if ((this.__ApplicationRef_30 == (null as any))) { (this.__ApplicationRef_30 = this._ApplicationRef__29); }
    return this.__ApplicationRef_30;
  }
  get _Compiler_31():import24.Compiler {
    if ((this.__Compiler_31 == (null as any))) { (this.__Compiler_31 = new import24.Compiler()); }
    return this.__Compiler_31;
  }
  get _APP_ID_32():any {
    if ((this.__APP_ID_32 == (null as any))) { (this.__APP_ID_32 = '%cmp%'); }
    return this.__APP_ID_32;
  }
  get _NodeSharedStylesHost_33():import25.NodeSharedStylesHost {
    if ((this.__NodeSharedStylesHost_33 == (null as any))) { (this.__NodeSharedStylesHost_33 = new import25.NodeSharedStylesHost()); }
    return this.__NodeSharedStylesHost_33;
  }
  get _DOCUMENT_34():any {
    if ((this.__DOCUMENT_34 == (null as any))) { (this.__DOCUMENT_34 = import4._document(this._NodeSharedStylesHost_33,this.parent.get(import48.NgZone))); }
    return this.__DOCUMENT_34;
  }
  get _NodeDomEventsPlugin_35():import4.NodeDomEventsPlugin {
    if ((this.__NodeDomEventsPlugin_35 == (null as any))) { (this.__NodeDomEventsPlugin_35 = new import4.NodeDomEventsPlugin()); }
    return this.__NodeDomEventsPlugin_35;
  }
  get _HAMMER_GESTURE_CONFIG_36():import26.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_36 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_36 = new import26.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_36;
  }
  get _EVENT_MANAGER_PLUGINS_37():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_37 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_37 = [
      this._NodeDomEventsPlugin_35,
      new import49.KeyEventsPlugin(),
      new import26.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_36)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_37;
  }
  get _NodeEventManager_38():import4.NodeEventManager {
    if ((this.__NodeEventManager_38 == (null as any))) { (this.__NodeEventManager_38 = new import4.NodeEventManager(this._EVENT_MANAGER_PLUGINS_37,this._DOCUMENT_34,this.parent.get(import48.NgZone))); }
    return this.__NodeEventManager_38;
  }
  get _EventManager_39():any {
    if ((this.__EventManager_39 == (null as any))) { (this.__EventManager_39 = this._NodeEventManager_38); }
    return this.__EventManager_39;
  }
  get _AnimationDriver_40():any {
    if ((this.__AnimationDriver_40 == (null as any))) { (this.__AnimationDriver_40 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_40;
  }
  get _NodeDomRootRenderer_41():import27.NodeDomRootRenderer {
    if ((this.__NodeDomRootRenderer_41 == (null as any))) { (this.__NodeDomRootRenderer_41 = new import27.NodeDomRootRenderer(this._DOCUMENT_34,this._EventManager_39,this._NodeSharedStylesHost_33,this._AnimationDriver_40)); }
    return this.__NodeDomRootRenderer_41;
  }
  get _DomRootRenderer_42():any {
    if ((this.__DomRootRenderer_42 == (null as any))) { (this.__DomRootRenderer_42 = this._NodeDomRootRenderer_41); }
    return this.__DomRootRenderer_42;
  }
  get _RootRenderer_43():any {
    if ((this.__RootRenderer_43 == (null as any))) { (this.__RootRenderer_43 = this._DomRootRenderer_42); }
    return this.__RootRenderer_43;
  }
  get _DomSanitizer_44():import28.DomSanitizerImpl {
    if ((this.__DomSanitizer_44 == (null as any))) { (this.__DomSanitizer_44 = new import28.DomSanitizerImpl()); }
    return this.__DomSanitizer_44;
  }
  get _Sanitizer_45():any {
    if ((this.__Sanitizer_45 == (null as any))) { (this.__Sanitizer_45 = this._DomSanitizer_44); }
    return this.__Sanitizer_45;
  }
  get _ViewUtils_46():import29.ViewUtils {
    if ((this.__ViewUtils_46 == (null as any))) { (this.__ViewUtils_46 = new import29.ViewUtils(this._RootRenderer_43,this._APP_ID_32,this._Sanitizer_45)); }
    return this.__ViewUtils_46;
  }
  get _IterableDiffers_47():any {
    if ((this.__IterableDiffers_47 == (null as any))) { (this.__IterableDiffers_47 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_47;
  }
  get _KeyValueDiffers_48():any {
    if ((this.__KeyValueDiffers_48 == (null as any))) { (this.__KeyValueDiffers_48 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_48;
  }
  get _ORIGIN_URL_49():any {
    if ((this.__ORIGIN_URL_49 == (null as any))) { (this.__ORIGIN_URL_49 = import4._ORIGIN_URL(this.parent.get(import48.NgZone))); }
    return this.__ORIGIN_URL_49;
  }
  get _REQUEST_URL_50():any {
    if ((this.__REQUEST_URL_50 == (null as any))) { (this.__REQUEST_URL_50 = import4._REQUEST_URL(this.parent.get(import48.NgZone))); }
    return this.__REQUEST_URL_50;
  }
  get _APP_BASE_HREF_51():any {
    if ((this.__APP_BASE_HREF_51 == (null as any))) { (this.__APP_BASE_HREF_51 = import4._APP_BASE_HREF(this.parent.get(import48.NgZone))); }
    return this.__APP_BASE_HREF_51;
  }
  get _PlatformLocation_52():import30.NodePlatformLocation {
    if ((this.__PlatformLocation_52 == (null as any))) { (this.__PlatformLocation_52 = new import30.NodePlatformLocation(this._ORIGIN_URL_49,this._REQUEST_URL_50,this._APP_BASE_HREF_51)); }
    return this.__PlatformLocation_52;
  }
  get _DomEventsPlugin_53():any[] {
    if ((this.__DomEventsPlugin_53 == (null as any))) { (this.__DomEventsPlugin_53 = [this._NodeDomEventsPlugin_35]); }
    return this.__DomEventsPlugin_53;
  }
  get _SharedStylesHost_54():any {
    if ((this.__SharedStylesHost_54 == (null as any))) { (this.__SharedStylesHost_54 = this._NodeSharedStylesHost_33); }
    return this.__SharedStylesHost_54;
  }
  get _DomSharedStylesHost_55():any {
    if ((this.__DomSharedStylesHost_55 == (null as any))) { (this.__DomSharedStylesHost_55 = this._NodeSharedStylesHost_33); }
    return this.__DomSharedStylesHost_55;
  }
  get _XSRFStrategy_56():any {
    if ((this.__XSRFStrategy_56 == (null as any))) { (this.__XSRFStrategy_56 = import5._noop); }
    return this.__XSRFStrategy_56;
  }
  get _BrowserXhr_57():any {
    if ((this.__BrowserXhr_57 == (null as any))) { (this.__BrowserXhr_57 = import5._noop); }
    return this.__BrowserXhr_57;
  }
  get _RequestOptions_58():import31.BaseRequestOptions {
    if ((this.__RequestOptions_58 == (null as any))) { (this.__RequestOptions_58 = new import31.BaseRequestOptions()); }
    return this.__RequestOptions_58;
  }
  get _ResponseOptions_59():import32.BaseResponseOptions {
    if ((this.__ResponseOptions_59 == (null as any))) { (this.__ResponseOptions_59 = new import32.BaseResponseOptions()); }
    return this.__ResponseOptions_59;
  }
  get _XHRBackend_60():import5.NodeBackend {
    if ((this.__XHRBackend_60 == (null as any))) { (this.__XHRBackend_60 = new import5.NodeBackend(this._ResponseOptions_59,this._BrowserXhr_57,this._XSRFStrategy_56,this.parent.get(import48.NgZone),this._APP_BASE_HREF_51,this._ORIGIN_URL_49)); }
    return this.__XHRBackend_60;
  }
  get _Http_61():any {
    if ((this.__Http_61 == (null as any))) { (this.__Http_61 = import5.httpFactory(this._XHRBackend_60,this._RequestOptions_58)); }
    return this.__Http_61;
  }
  get _JSONPBackend_62():import5.NodeJsonpBackend_ {
    if ((this.__JSONPBackend_62 == (null as any))) { (this.__JSONPBackend_62 = new import5.NodeJsonpBackend_(this._ResponseOptions_59,this.parent.get(import48.NgZone),this._APP_BASE_HREF_51,this._ORIGIN_URL_49)); }
    return this.__JSONPBackend_62;
  }
  get _Jsonp_63():any {
    if ((this.__Jsonp_63 == (null as any))) { (this.__Jsonp_63 = import5.jsonpFactory(this._JSONPBackend_62,this._RequestOptions_58)); }
    return this.__Jsonp_63;
  }
  get _RadioControlRegistry_64():import33.RadioControlRegistry {
    if ((this.__RadioControlRegistry_64 == (null as any))) { (this.__RadioControlRegistry_64 = new import33.RadioControlRegistry()); }
    return this.__RadioControlRegistry_64;
  }
  get _FormBuilder_65():import34.FormBuilder {
    if ((this.__FormBuilder_65 == (null as any))) { (this.__FormBuilder_65 = new import34.FormBuilder()); }
    return this.__FormBuilder_65;
  }
  get _ROUTES_66():any[] {
    if ((this.__ROUTES_66 == (null as any))) { (this.__ROUTES_66 = [
        [{
          path: 'home',
          component: import50.HomeComponent
        }
      ],
        [{
          path: 'about',
          component: import51.AboutComponent
        }
      ],
        [{
          path: 'todo',
          component: import52.TodoComponent
        }
      ],
      [
        {
          path: '',
          redirectTo: '/home',
          pathMatch: 'full'
        }
        ,
        {
          path: 'lazy',
          loadChildren: import17.getLazyModule
        }

      ]
      ,
      ([] as any[])
    ]
    ); }
    return this.__ROUTES_66;
  }
  get _ROUTER_CONFIGURATION_67():any {
    if ((this.__ROUTER_CONFIGURATION_67 == (null as any))) { (this.__ROUTER_CONFIGURATION_67 = {useHash: false}); }
    return this.__ROUTER_CONFIGURATION_67;
  }
  get _LocationStrategy_68():any {
    if ((this.__LocationStrategy_68 == (null as any))) { (this.__LocationStrategy_68 = import9.provideLocationStrategy(this._PlatformLocation_52,this._APP_BASE_HREF_51,this._ROUTER_CONFIGURATION_67)); }
    return this.__LocationStrategy_68;
  }
  get _Location_69():import35.Location {
    if ((this.__Location_69 == (null as any))) { (this.__Location_69 = new import35.Location(this._LocationStrategy_68)); }
    return this.__Location_69;
  }
  get _UrlSerializer_70():import36.DefaultUrlSerializer {
    if ((this.__UrlSerializer_70 == (null as any))) { (this.__UrlSerializer_70 = new import36.DefaultUrlSerializer()); }
    return this.__UrlSerializer_70;
  }
  get _RouterOutletMap_71():import37.RouterOutletMap {
    if ((this.__RouterOutletMap_71 == (null as any))) { (this.__RouterOutletMap_71 = new import37.RouterOutletMap()); }
    return this.__RouterOutletMap_71;
  }
  get _NgModuleFactoryLoader_72():import38.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_72 == (null as any))) { (this.__NgModuleFactoryLoader_72 = new import38.SystemJsNgModuleLoader(this._Compiler_31,this.parent.get(import38.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_72;
  }
  get _Router_73():any {
    if ((this.__Router_73 == (null as any))) { (this.__Router_73 = import9.setupRouter(this._ApplicationRef_30,this._UrlSerializer_70,this._RouterOutletMap_71,this._Location_69,this,this._NgModuleFactoryLoader_72,this._Compiler_31,this._ROUTES_66,this._ROUTER_CONFIGURATION_67)); }
    return this.__Router_73;
  }
  get _ActivatedRoute_74():any {
    if ((this.__ActivatedRoute_74 == (null as any))) { (this.__ActivatedRoute_74 = import9.rootRoute(this._Router_73)); }
    return this.__ActivatedRoute_74;
  }
  get _PreloadAllModules_78():import39.PreloadAllModules {
    if ((this.__PreloadAllModules_78 == (null as any))) { (this.__PreloadAllModules_78 = new import39.PreloadAllModules()); }
    return this.__PreloadAllModules_78;
  }
  get _APP_BOOTSTRAP_LISTENER_79():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_79 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_79 = [import9.initialRouterNavigation(this._Router_73,this._ApplicationRef_30,this._RouterPreloader_77,this._ROUTER_CONFIGURATION_67)]); }
    return this.__APP_BOOTSTRAP_LISTENER_79;
  }
  get _ApiService_80():import40.ApiService {
    if ((this.__ApiService_80 == (null as any))) { (this.__ApiService_80 = new import40.ApiService(this._Http_61)); }
    return this.__ApiService_80;
  }
  get _ModelService_81():import41.ModelService {
    if ((this.__ModelService_81 == (null as any))) { (this.__ModelService_81 = new import41.ModelService(this._ApiService_80,this._CacheService_21)); }
    return this.__ModelService_81;
  }
  get _isBrowser_82():any {
    if ((this.__isBrowser_82 == (null as any))) { (this.__isBrowser_82 = import53.isBrowser); }
    return this.__isBrowser_82;
  }
  get _isNode_83():any {
    if ((this.__isNode_83 == (null as any))) { (this.__isNode_83 = true); }
    return this.__isNode_83;
  }
  get _req_84():any {
    if ((this.__req_84 == (null as any))) { (this.__req_84 = import1.getRequest()); }
    return this.__req_84;
  }
  get _res_85():any {
    if ((this.__res_85 == (null as any))) { (this.__res_85 = import1.getResponse()); }
    return this.__res_85;
  }
  get _Meta_86():import42.Meta {
    if ((this.__Meta_86 == (null as any))) { (this.__Meta_86 = new import42.Meta()); }
    return this.__Meta_86;
  }
  createInternal():import1.MainModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._NodeModule_2 = new import4.NodeModule(this.parent.get(import4.NodeModule,(null as any)));
    this._NodeHttpModule_3 = new import5.NodeHttpModule();
    this._NodeJsonpModule_4 = new import5.NodeJsonpModule();
    this._UniversalModule_5 = new import6.UniversalModule();
    this._InternalFormsSharedModule_6 = new import7.InternalFormsSharedModule();
    this._FormsModule_7 = new import8.FormsModule();
    this._ROUTER_FORROOT_GUARD_8 = import9.provideForRootGuard(this.parent.get(import54.Router,(null as any)));
    this._RouterModule_9 = new import9.RouterModule(this._ROUTER_FORROOT_GUARD_8);
    this._ReactiveFormsModule_10 = new import8.ReactiveFormsModule();
    this._SharedModule_11 = new import10.SharedModule();
    this._HomeRoutingModule_12 = new import11.HomeRoutingModule();
    this._HomeModule_13 = new import12.HomeModule();
    this._AboutRoutingModule_14 = new import13.AboutRoutingModule();
    this._AboutModule_15 = new import14.AboutModule();
    this._TodoRoutingModule_16 = new import15.TodoRoutingModule();
    this._TodoModule_17 = new import16.TodoModule();
    this._AppRoutingModule_18 = new import17.AppRoutingModule();
    this._AppModule_19 = new import18.AppModule();
    this._LRU_20 = import1.getLRU();
    this._CacheService_21 = new import19.CacheService(this._LRU_20);
    this._MainModule_22 = new import1.MainModule(this._CacheService_21);
    this._ErrorHandler_25 = import4._errorHandler();
    this._ApplicationInitStatus_26 = new import21.ApplicationInitStatus(this.parent.get(import21.APP_INITIALIZER,(null as any)));
    this._TestabilityRegistry_27 = new import4.MockTestabilityRegistry();
    this._Testability_28 = new import22.Testability(this.parent.get(import48.NgZone));
    this._ApplicationRef__29 = new import23.ApplicationRef_(this.parent.get(import48.NgZone),this.parent.get(import55.Console),this,this._ErrorHandler_25,this,this._ApplicationInitStatus_26,this._TestabilityRegistry_27,this._Testability_28);
    this._NoPreloading_75 = new import39.NoPreloading();
    this._PreloadingStrategy_76 = this._NoPreloading_75;
    this._RouterPreloader_77 = new import39.RouterPreloader(this._Router_73,this._NgModuleFactoryLoader_72,this._Compiler_31,this,this._PreloadingStrategy_76);
    return this._MainModule_22;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.NodeModule)) { return this._NodeModule_2; }
    if ((token === import5.NodeHttpModule)) { return this._NodeHttpModule_3; }
    if ((token === import5.NodeJsonpModule)) { return this._NodeJsonpModule_4; }
    if ((token === import6.UniversalModule)) { return this._UniversalModule_5; }
    if ((token === import7.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_6; }
    if ((token === import8.FormsModule)) { return this._FormsModule_7; }
    if ((token === import9.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_8; }
    if ((token === import9.RouterModule)) { return this._RouterModule_9; }
    if ((token === import8.ReactiveFormsModule)) { return this._ReactiveFormsModule_10; }
    if ((token === import10.SharedModule)) { return this._SharedModule_11; }
    if ((token === import11.HomeRoutingModule)) { return this._HomeRoutingModule_12; }
    if ((token === import12.HomeModule)) { return this._HomeModule_13; }
    if ((token === import13.AboutRoutingModule)) { return this._AboutRoutingModule_14; }
    if ((token === import14.AboutModule)) { return this._AboutModule_15; }
    if ((token === import15.TodoRoutingModule)) { return this._TodoRoutingModule_16; }
    if ((token === import16.TodoModule)) { return this._TodoModule_17; }
    if ((token === import17.AppRoutingModule)) { return this._AppRoutingModule_18; }
    if ((token === import18.AppModule)) { return this._AppModule_19; }
    if ((token === 'LRU')) { return this._LRU_20; }
    if ((token === import19.CacheService)) { return this._CacheService_21; }
    if ((token === import1.MainModule)) { return this._MainModule_22; }
    if ((token === import56.LOCALE_ID)) { return this._LOCALE_ID_23; }
    if ((token === import20.NgLocalization)) { return this._NgLocalization_24; }
    if ((token === import57.ErrorHandler)) { return this._ErrorHandler_25; }
    if ((token === import21.ApplicationInitStatus)) { return this._ApplicationInitStatus_26; }
    if ((token === import22.TestabilityRegistry)) { return this._TestabilityRegistry_27; }
    if ((token === import22.Testability)) { return this._Testability_28; }
    if ((token === import23.ApplicationRef_)) { return this._ApplicationRef__29; }
    if ((token === import23.ApplicationRef)) { return this._ApplicationRef_30; }
    if ((token === import24.Compiler)) { return this._Compiler_31; }
    if ((token === import58.APP_ID)) { return this._APP_ID_32; }
    if ((token === import25.NodeSharedStylesHost)) { return this._NodeSharedStylesHost_33; }
    if ((token === import59.DOCUMENT)) { return this._DOCUMENT_34; }
    if ((token === import4.NodeDomEventsPlugin)) { return this._NodeDomEventsPlugin_35; }
    if ((token === import26.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_36; }
    if ((token === import60.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_37; }
    if ((token === import4.NodeEventManager)) { return this._NodeEventManager_38; }
    if ((token === import60.EventManager)) { return this._EventManager_39; }
    if ((token === import61.AnimationDriver)) { return this._AnimationDriver_40; }
    if ((token === import27.NodeDomRootRenderer)) { return this._NodeDomRootRenderer_41; }
    if ((token === import62.DomRootRenderer)) { return this._DomRootRenderer_42; }
    if ((token === import63.RootRenderer)) { return this._RootRenderer_43; }
    if ((token === import28.DomSanitizer)) { return this._DomSanitizer_44; }
    if ((token === import64.Sanitizer)) { return this._Sanitizer_45; }
    if ((token === import29.ViewUtils)) { return this._ViewUtils_46; }
    if ((token === import65.IterableDiffers)) { return this._IterableDiffers_47; }
    if ((token === import66.KeyValueDiffers)) { return this._KeyValueDiffers_48; }
    if ((token === import67.ORIGIN_URL)) { return this._ORIGIN_URL_49; }
    if ((token === import67.REQUEST_URL)) { return this._REQUEST_URL_50; }
    if ((token === import68.APP_BASE_HREF)) { return this._APP_BASE_HREF_51; }
    if ((token === import69.PlatformLocation)) { return this._PlatformLocation_52; }
    if ((token === import70.DomEventsPlugin)) { return this._DomEventsPlugin_53; }
    if ((token === import71.SharedStylesHost)) { return this._SharedStylesHost_54; }
    if ((token === import71.DomSharedStylesHost)) { return this._DomSharedStylesHost_55; }
    if ((token === import72.XSRFStrategy)) { return this._XSRFStrategy_56; }
    if ((token === import73.BrowserXhr)) { return this._BrowserXhr_57; }
    if ((token === import31.RequestOptions)) { return this._RequestOptions_58; }
    if ((token === import32.ResponseOptions)) { return this._ResponseOptions_59; }
    if ((token === import74.XHRBackend)) { return this._XHRBackend_60; }
    if ((token === import75.Http)) { return this._Http_61; }
    if ((token === import76.JSONPBackend)) { return this._JSONPBackend_62; }
    if ((token === import75.Jsonp)) { return this._Jsonp_63; }
    if ((token === import33.RadioControlRegistry)) { return this._RadioControlRegistry_64; }
    if ((token === import34.FormBuilder)) { return this._FormBuilder_65; }
    if ((token === import77.ROUTES)) { return this._ROUTES_66; }
    if ((token === import9.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_67; }
    if ((token === import68.LocationStrategy)) { return this._LocationStrategy_68; }
    if ((token === import35.Location)) { return this._Location_69; }
    if ((token === import36.UrlSerializer)) { return this._UrlSerializer_70; }
    if ((token === import37.RouterOutletMap)) { return this._RouterOutletMap_71; }
    if ((token === import78.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_72; }
    if ((token === import54.Router)) { return this._Router_73; }
    if ((token === import79.ActivatedRoute)) { return this._ActivatedRoute_74; }
    if ((token === import39.NoPreloading)) { return this._NoPreloading_75; }
    if ((token === import39.PreloadingStrategy)) { return this._PreloadingStrategy_76; }
    if ((token === import39.RouterPreloader)) { return this._RouterPreloader_77; }
    if ((token === import39.PreloadAllModules)) { return this._PreloadAllModules_78; }
    if ((token === import58.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_79; }
    if ((token === import40.ApiService)) { return this._ApiService_80; }
    if ((token === import41.ModelService)) { return this._ModelService_81; }
    if ((token === 'isBrowser')) { return this._isBrowser_82; }
    if ((token === 'isNode')) { return this._isNode_83; }
    if ((token === 'req')) { return this._req_84; }
    if ((token === 'res')) { return this._res_85; }
    if ((token === import42.Meta)) { return this._Meta_86; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__29.ngOnDestroy();
    this._RouterPreloader_77.ngOnDestroy();
  }
}
export const MainModuleNgFactory:import0.NgModuleFactory<import1.MainModule> = new import0.NgModuleFactory(MainModuleInjector,import1.MainModule);