/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './todo.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../shared/model/model.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './todo.component.css.shim';
import * as import12 from '../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import13 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import14 from '../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import15 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import16 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import17 from '@angular/common/src/pipes/date_pipe';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import21 from '@angular/core/src/i18n/tokens';
import * as import22 from '@angular/forms/src/directives/default_value_accessor';
import * as import23 from '@angular/forms/src/directives/control_value_accessor';
import * as import24 from '@angular/forms/src/directives/ng_model';
import * as import25 from '@angular/forms/src/directives/ng_control';
import * as import26 from '@angular/forms/src/directives/ng_control_status';
import * as import27 from '@angular/forms/src/directives/ng_form';
import * as import28 from '@angular/forms/src/directives/control_container';
import * as import29 from '@angular/common/src/directives/ng_for';
export class Wrapper_TodoComponent {
  context:import0.TodoComponent;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.TodoComponent(p0);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_TodoComponent_Host:import2.RenderComponentType = (null as any);
class _View_TodoComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TodoComponent_0_4:Wrapper_TodoComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TodoComponent_Host0,renderType_TodoComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'todo',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TodoComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TodoComponent_0_4 = new Wrapper_TodoComponent(this.parentInjector.get(import8.ModelService));
    this._appEl_0.initComponent(this._TodoComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._TodoComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TodoComponent) && (0 === requestNodeIndex))) { return this._TodoComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TodoComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._TodoComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TodoComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_TodoComponent_Host === (null as any))) { (renderType_TodoComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_TodoComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TodoComponentNgFactory:import10.ComponentFactory<import0.TodoComponent> = new import10.ComponentFactory<import0.TodoComponent>('todo',viewFactory_TodoComponent_Host0,import0.TodoComponent);
const styles_TodoComponent:any[] = [import11.styles];
var renderType_TodoComponent:import2.RenderComponentType = (null as any);
class _View_TodoComponent0 extends import1.AppView<import0.TodoComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _NgForm_2_3:import12.Wrapper_NgForm;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import13.Wrapper_NgControlStatusGroup;
  _text_3:any;
  _el_4:any;
  _DefaultValueAccessor_4_3:import14.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_4_4:any[];
  _NgModel_4_5:import15.Wrapper_NgModel;
  _NgControl_4_6:any;
  _NgControlStatus_4_7:import13.Wrapper_NgControlStatus;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _TemplateRef_27_5:any;
  _NgFor_27_6:import16.Wrapper_NgFor;
  _text_28:any;
  _text_29:any;
  _pipe_date_0:import17.DatePipe;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TodoComponent0,renderType_TodoComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','todo'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  Todo component\n    ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'form',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._NgForm_2_3 = new import12.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_2_4 = this._NgForm_2_3.context;
    this._NgControlStatusGroup_2_5 = new import13.Wrapper_NgControlStatusGroup(this._ControlContainer_2_4);
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'input',new import4.InlineArray2(2,'name','newTodo'),(null as any));
    this._DefaultValueAccessor_4_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_4));
    this._NG_VALUE_ACCESSOR_4_4 = [this._DefaultValueAccessor_4_3.context];
    this._NgModel_4_5 = new import15.Wrapper_NgModel(this._ControlContainer_2_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_4_4);
    this._NgControl_4_6 = this._NgModel_4_5.context;
    this._NgControlStatus_4_7 = new import13.Wrapper_NgControlStatus(this._NgControl_4_6);
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_2,'button',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Submit',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','table'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._el_12 = import4.createRenderElement(this.renderer,this._el_10,'div',new import4.InlineArray2(2,'class','row header'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_12,'div',new import4.InlineArray2(2,'class','cell'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'Id',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_12,'div',new import4.InlineArray2(2,'class','cell'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Created at',(null as any));
    this._text_19 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_12,'div',new import4.InlineArray2(2,'class','cell'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Value',(null as any));
    this._text_22 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._el_23 = import4.createRenderElement(this.renderer,this._el_12,'div',new import4.InlineArray2(2,'class','cell'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Completed',(null as any));
    this._text_25 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._appEl_27 = new import3.AppElement(27,10,this,this._anchor_27);
    this._TemplateRef_27_5 = new import19.TemplateRef_(this._appEl_27,viewFactory_TodoComponent1);
    this._NgFor_27_6 = new import16.Wrapper_NgFor(this._appEl_27.vcRef,this._TemplateRef_27_5,this.parentInjector.get(import20.IterableDiffers),this.ref);
    this._text_28 = this.renderer.createText(this._el_10,'\n\n',(null as any));
    this._text_29 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'ngSubmit',this.eventHandler(this._handle_ngSubmit_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_2,'submit',this.eventHandler(this._handle_submit_2_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_2,'reset',this.eventHandler(this._handle_reset_2_2.bind(this)));
    const subscription_0:any = this._NgForm_2_3.context.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_2_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_4,'ngModelChange',this.eventHandler(this._handle_ngModelChange_4_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_4,'input',this.eventHandler(this._handle_input_4_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_4,'blur',this.eventHandler(this._handle_blur_4_2.bind(this)));
    const subscription_1:any = this._NgModel_4_5.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_4_0.bind(this)));
    this._pipe_date_0 = new import17.DatePipe(this.parentInjector.get(import21.LOCALE_ID));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._text_29
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.DefaultValueAccessor) && (4 === requestNodeIndex))) { return this._DefaultValueAccessor_4_3.context; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (4 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_4_4; }
    if (((token === import24.NgModel) && (4 === requestNodeIndex))) { return this._NgModel_4_5.context; }
    if (((token === import25.NgControl) && (4 === requestNodeIndex))) { return this._NgControl_4_6; }
    if (((token === import26.NgControlStatus) && (4 === requestNodeIndex))) { return this._NgControlStatus_4_7.context; }
    if (((token === import27.NgForm) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._NgForm_2_3.context; }
    if (((token === import28.ControlContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ControlContainer_2_4; }
    if (((token === import26.NgControlStatusGroup) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._NgControlStatusGroup_2_5.context; }
    if (((token === import19.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import29.NgFor) && (27 === requestNodeIndex))) { return this._NgFor_27_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_2_3.detectChangesInInputProps(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.detectChangesInInputProps(this,this._el_2,throwOnChange);
    this._DefaultValueAccessor_4_3.detectChangesInInputProps(this,this._el_4,throwOnChange);
    const currVal_4_1_0:any = 'newTodo';
    this._NgModel_4_5.check_name(currVal_4_1_0,throwOnChange,false);
    const currVal_4_1_1:any = this.context.newValue;
    this._NgModel_4_5.check_model(currVal_4_1_1,throwOnChange,false);
    this._NgModel_4_5.detectChangesInInputProps(this,this._el_4,throwOnChange);
    this._NgControlStatus_4_7.detectChangesInInputProps(this,this._el_4,throwOnChange);
    const currVal_27_0_0:any = this.context.todos;
    this._NgFor_27_6.check_ngForOf(currVal_27_0_0,throwOnChange,false);
    this._NgFor_27_6.detectChangesInInputProps(this,this._anchor_27,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._NgForm_2_3.detectChangesInHostProps(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.detectChangesInHostProps(this,this._el_2,throwOnChange);
    this._DefaultValueAccessor_4_3.detectChangesInHostProps(this,this._el_4,throwOnChange);
    this._NgModel_4_5.detectChangesInHostProps(this,this._el_4,throwOnChange);
    this._NgControlStatus_4_7.detectChangesInHostProps(this,this._el_4,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_4_5.context.ngOnDestroy();
  }
  private _handle_ngSubmit_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_2_0:any = ((<any>this.context.addTodo()) !== false);
    return (true && pd_2_0);
  }
  private _handle_submit_2_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_2_0:any = ((<any>this._NgForm_2_3.context.onSubmit($event)) !== false);
    return (true && pd_2_0);
  }
  private _handle_reset_2_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_2_0:any = ((<any>this._NgForm_2_3.context.onReset()) !== false);
    return (true && pd_2_0);
  }
  private _handle_ngModelChange_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_4_0:any = ((<any>(this.context.newValue = $event)) !== false);
    return (true && pd_4_0);
  }
  private _handle_input_4_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_4_0:any = ((<any>this._DefaultValueAccessor_4_3.context.onChange($event.target.value)) !== false);
    return (true && pd_4_0);
  }
  private _handle_blur_4_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_4_0:any = ((<any>this._DefaultValueAccessor_4_3.context.onTouched()) !== false);
    return (true && pd_4_0);
  }
}
export function viewFactory_TodoComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.TodoComponent> {
  if ((renderType_TodoComponent === (null as any))) { (renderType_TodoComponent = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.Emulated,styles_TodoComponent,{})); }
  return new _View_TodoComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_TodoComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  _pipe_date_0_0:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TodoComponent1,renderType_TodoComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','cell'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','cell'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','cell'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','cell'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._pipe_date_0_0 = import4.pureProxy2((<_View_TodoComponent0>this.parent)._pipe_date_0.transform.bind((<_View_TodoComponent0>this.parent)._pipe_date_0));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_14:any = import4.interpolate(1,'',this.context.$implicit.id,'');
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setText(this._text_3,currVal_14);
      this._expr_14 = currVal_14;
    }
    valUnwrapper.reset();
    const currVal_15:any = import4.interpolate(1,'',valUnwrapper.unwrap(import4.castByValue(this._pipe_date_0_0,(<_View_TodoComponent0>this.parent)._pipe_date_0.transform)(this.context.$implicit.created_at,'dd/MM/yyyy HH:mm:ss')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_15,currVal_15))) {
      this.renderer.setText(this._text_6,currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_17:any = import4.interpolate(1,'',this.context.$implicit.value,'');
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setText(this._text_9,currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = import4.interpolate(1,'',this.context.$implicit.completed,'');
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setText(this._text_12,currVal_18);
      this._expr_18 = currVal_18;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TodoComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_TodoComponent1(viewUtils,parentInjector,declarationEl);
}