/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.table[_ngcontent-%COMP%] {\r\n  padding-top: 30px;\r\n}\r\n.row[_ngcontent-%COMP%] {\r\n  display: table-row;\r\n  background: #f6f6f6;\r\n}\r\n\r\n.row[_ngcontent-%COMP%]:nth-of-type(odd) {\r\n  background: #e9e9e9;\r\n}\r\n\r\n.row.header[_ngcontent-%COMP%] {\r\n  color: #ffffff;\r\n  font-weight: bold;\r\n  background: #158126;\r\n}\r\n\r\n.cell[_ngcontent-%COMP%] {\r\n  padding: 20px;\r\n  display: table-cell;\r\n}'];