/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app-routing.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/core/src/di/injector';
import * as import4 from '@angular/router/src/router_config_loader';
class AppRoutingModuleInjector extends import0.NgModuleInjector<import1.AppRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _AppRoutingModule_1:import1.AppRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import3.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _ROUTES_2():any[] {
      if ((this.__ROUTES_2 == (null as any))) { (this.__ROUTES_2 = [[
        {
          path: '',
          redirectTo: '/home',
          pathMatch: 'full'
        }
        ,
        {
          path: 'lazy',
          loadChildren: import1.getLazyModule
        }

      ]
    ]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.AppRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ROUTER_FORROOT_GUARD,(null as any)));
    this._AppRoutingModule_1 = new import1.AppRoutingModule();
    return this._AppRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.AppRoutingModule)) { return this._AppRoutingModule_1; }
    if ((token === import4.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AppRoutingModuleNgFactory:import0.NgModuleFactory<import1.AppRoutingModule> = new import0.NgModuleFactory(AppRoutingModuleInjector,import1.AppRoutingModule);