/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/router/src/router_module';
import * as import4 from '@angular/forms/src/directives';
import * as import5 from '@angular/forms/src/form_providers';
import * as import6 from './shared/shared.module';
import * as import7 from './+home/home-routing.module';
import * as import8 from './+home/home.module';
import * as import9 from './+about/about-routing.module';
import * as import10 from './+about/about.module';
import * as import11 from './+todo/todo-routing.module';
import * as import12 from './+todo/todo.module';
import * as import13 from './app-routing.module';
import * as import14 from '@angular/common/src/localization';
import * as import15 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import16 from '@angular/forms/src/form_builder';
import * as import17 from '@angular/core/src/di/injector';
import * as import18 from './+home/home.component.ngfactory';
import * as import19 from './+about/about.component.ngfactory';
import * as import20 from './+todo/todo.component.ngfactory';
import * as import21 from '@angular/core/src/i18n/tokens';
import * as import22 from './+home/home.component';
import * as import23 from './+about/about.component';
import * as import24 from './+todo/todo.component';
import * as import25 from '@angular/router/src/router_config_loader';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _InternalFormsSharedModule_2:import4.InternalFormsSharedModule;
  _FormsModule_3:import5.FormsModule;
  _ReactiveFormsModule_4:import5.ReactiveFormsModule;
  _SharedModule_5:import6.SharedModule;
  _HomeRoutingModule_6:import7.HomeRoutingModule;
  _HomeModule_7:import8.HomeModule;
  _AboutRoutingModule_8:import9.AboutRoutingModule;
  _AboutModule_9:import10.AboutModule;
  _TodoRoutingModule_10:import11.TodoRoutingModule;
  _TodoModule_11:import12.TodoModule;
  _AppRoutingModule_12:import13.AppRoutingModule;
  _AppModule_13:import1.AppModule;
  __NgLocalization_14:import14.NgLocaleLocalization;
  __RadioControlRegistry_15:import15.RadioControlRegistry;
  __FormBuilder_16:import16.FormBuilder;
  __ROUTES_17:any[];
  constructor(parent:import17.Injector) {
    super(parent,[
      import18.HomeComponentNgFactory,
      import19.AboutComponentNgFactory,
      import20.TodoComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_14():import14.NgLocaleLocalization {
    if ((this.__NgLocalization_14 == (null as any))) { (this.__NgLocalization_14 = new import14.NgLocaleLocalization(this.parent.get(import21.LOCALE_ID))); }
    return this.__NgLocalization_14;
  }
  get _RadioControlRegistry_15():import15.RadioControlRegistry {
    if ((this.__RadioControlRegistry_15 == (null as any))) { (this.__RadioControlRegistry_15 = new import15.RadioControlRegistry()); }
    return this.__RadioControlRegistry_15;
  }
  get _FormBuilder_16():import16.FormBuilder {
    if ((this.__FormBuilder_16 == (null as any))) { (this.__FormBuilder_16 = new import16.FormBuilder()); }
    return this.__FormBuilder_16;
  }
  get _ROUTES_17():any[] {
    if ((this.__ROUTES_17 == (null as any))) { (this.__ROUTES_17 = [
        [{
          path: 'home',
          component: import22.HomeComponent
        }
      ],
        [{
          path: 'about',
          component: import23.AboutComponent
        }
      ],
        [{
          path: 'todo',
          component: import24.TodoComponent
        }
      ],
      [
        {
          path: '',
          redirectTo: '/home',
          pathMatch: 'full'
        }
        ,
        {
          path: 'lazy',
          loadChildren: import13.getLazyModule
        }

      ]

    ]
    ); }
    return this.__ROUTES_17;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ROUTER_FORROOT_GUARD,(null as any)));
    this._InternalFormsSharedModule_2 = new import4.InternalFormsSharedModule();
    this._FormsModule_3 = new import5.FormsModule();
    this._ReactiveFormsModule_4 = new import5.ReactiveFormsModule();
    this._SharedModule_5 = new import6.SharedModule();
    this._HomeRoutingModule_6 = new import7.HomeRoutingModule();
    this._HomeModule_7 = new import8.HomeModule();
    this._AboutRoutingModule_8 = new import9.AboutRoutingModule();
    this._AboutModule_9 = new import10.AboutModule();
    this._TodoRoutingModule_10 = new import11.TodoRoutingModule();
    this._TodoModule_11 = new import12.TodoModule();
    this._AppRoutingModule_12 = new import13.AppRoutingModule();
    this._AppModule_13 = new import1.AppModule();
    return this._AppModule_13;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import4.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_2; }
    if ((token === import5.FormsModule)) { return this._FormsModule_3; }
    if ((token === import5.ReactiveFormsModule)) { return this._ReactiveFormsModule_4; }
    if ((token === import6.SharedModule)) { return this._SharedModule_5; }
    if ((token === import7.HomeRoutingModule)) { return this._HomeRoutingModule_6; }
    if ((token === import8.HomeModule)) { return this._HomeModule_7; }
    if ((token === import9.AboutRoutingModule)) { return this._AboutRoutingModule_8; }
    if ((token === import10.AboutModule)) { return this._AboutModule_9; }
    if ((token === import11.TodoRoutingModule)) { return this._TodoRoutingModule_10; }
    if ((token === import12.TodoModule)) { return this._TodoModule_11; }
    if ((token === import13.AppRoutingModule)) { return this._AppRoutingModule_12; }
    if ((token === import1.AppModule)) { return this._AppModule_13; }
    if ((token === import14.NgLocalization)) { return this._NgLocalization_14; }
    if ((token === import15.RadioControlRegistry)) { return this._RadioControlRegistry_15; }
    if ((token === import16.FormBuilder)) { return this._FormBuilder_16; }
    if ((token === import25.ROUTES)) { return this._ROUTES_17; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);