/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import11 from '../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import14 from '@angular/router/src/router';
import * as import15 from '@angular/router/src/router_state';
import * as import16 from '@angular/common/src/location/location_strategy';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/router/src/router_outlet_map';
import * as import19 from '@angular/core/src/linker/component_factory_resolver';
import * as import20 from '@angular/router/src/directives/router_link';
import * as import21 from '@angular/router/src/directives/router_link_active';
import * as import22 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  context:import0.AppComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.AppComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
export class Wrapper_XLargeDirective {
  context:import0.XLargeDirective;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.XLargeDirective(p0,p1);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AppComponent_0_4:Wrapper_AppComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'app',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new Wrapper_AppComponent();
    this._appEl_0.initComponent(this._AppComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AppComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._AppComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import9.ComponentFactory<import0.AppComponent> = new import9.ComponentFactory<import0.AppComponent>('app',viewFactory_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ['*[_ngcontent-%COMP%] { padding:0; margin:0; font-family: \'Droid Sans\', sans-serif; }\n    #universal[_ngcontent-%COMP%] { text-align:center; font-weight:bold; padding:15px 0; }\n    nav[_ngcontent-%COMP%] { background:#158126; min-height:40px; border-bottom:5px #046923 solid; }\n    nav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] { font-weight:bold; text-decoration:none; color:#fff; padding:20px; display:inline-block; }\n    nav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover { background:#00AF36; }\n    .hero-universal[_ngcontent-%COMP%] { min-height:500px; display:block; padding:20px; background: url(\'/assets/logo.png\') no-repeat center center; }\n    .inner-hero[_ngcontent-%COMP%] { background: rgba(255, 255, 255, 0.75); border:5px #ccc solid; padding:25px; }\n    .router-link-active[_ngcontent-%COMP%] { background-color: #00AF36; }\n    main[_ngcontent-%COMP%] { padding:20px 0; }\n    pre[_ngcontent-%COMP%] { font-size:12px; }'];
var renderType_AppComponent:import2.RenderComponentType = (null as any);
class _View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _RouterLinkWithHref_6_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_6_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_6_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_6_1:import12.QueryList<any>;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _RouterLinkWithHref_9_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_9_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_9_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_9_1:import12.QueryList<any>;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _RouterLinkWithHref_12_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_12_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_12_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_12_1:import12.QueryList<any>;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _RouterLinkWithHref_15_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_15_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_15_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_15_1:import12.QueryList<any>;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _XLargeDirective_25_3:Wrapper_XLargeDirective;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  /*private*/ _appEl_40:import3.AppElement;
  _RouterOutlet_40_5:import13.Wrapper_RouterOutlet;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  /*private*/ _expr_64:any;
  /*private*/ _expr_65:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_64 = import7.UNINITIALIZED;
    this._expr_65 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._el_1 = import4.createRenderElement(this.renderer,parentRenderNode,'h3',new import4.InlineArray2(2,'id','universal'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'Angular2 Universal',(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,parentRenderNode,'nav',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'a',new import4.InlineArray4(4,'routerLink','home','routerLinkActive','router-link-active'),(null as any));
    this._RouterLinkWithHref_6_3 = new import10.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._RouterLinkActive_6_4 = new import11.Wrapper_RouterLinkActive(this.parentInjector.get(import14.Router),new import17.ElementRef(this._el_6),this.renderer);
    this._query_RouterLink_6_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_6_1 = new import12.QueryList<any>();
    this._text_7 = this.renderer.createText(this._el_6,'Home',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_4,'a',new import4.InlineArray4(4,'routerLink','about','routerLinkActive','router-link-active'),(null as any));
    this._RouterLinkWithHref_9_3 = new import10.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._RouterLinkActive_9_4 = new import11.Wrapper_RouterLinkActive(this.parentInjector.get(import14.Router),new import17.ElementRef(this._el_9),this.renderer);
    this._query_RouterLink_9_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_9_1 = new import12.QueryList<any>();
    this._text_10 = this.renderer.createText(this._el_9,'About',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_12 = import4.createRenderElement(this.renderer,this._el_4,'a',new import4.InlineArray4(4,'routerLink','todo','routerLinkActive','router-link-active'),(null as any));
    this._RouterLinkWithHref_12_3 = new import10.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._RouterLinkActive_12_4 = new import11.Wrapper_RouterLinkActive(this.parentInjector.get(import14.Router),new import17.ElementRef(this._el_12),this.renderer);
    this._query_RouterLink_12_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_12_1 = new import12.QueryList<any>();
    this._text_13 = this.renderer.createText(this._el_12,'Todo',(null as any));
    this._text_14 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_15 = import4.createRenderElement(this.renderer,this._el_4,'a',new import4.InlineArray4(4,'routerLink','lazy','routerLinkActive','router-link-active'),(null as any));
    this._RouterLinkWithHref_15_3 = new import10.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._RouterLinkActive_15_4 = new import11.Wrapper_RouterLinkActive(this.parentInjector.get(import14.Router),new import17.ElementRef(this._el_15),this.renderer);
    this._query_RouterLink_15_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_15_1 = new import12.QueryList<any>();
    this._text_16 = this.renderer.createText(this._el_15,'Lazy',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n  ',(null as any));
    this._text_18 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._el_19 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','hero-universal'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._el_21 = import4.createRenderElement(this.renderer,this._el_19,'div',new import4.InlineArray2(2,'class','inner-hero'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n      ',(null as any));
    this._el_23 = import4.createRenderElement(this.renderer,this._el_21,'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._el_25 = import4.createRenderElement(this.renderer,this._el_23,'span',new import4.InlineArray2(2,'xLarge',''),(null as any));
    this._XLargeDirective_25_3 = new Wrapper_XLargeDirective(new import17.ElementRef(this._el_25),this.renderer);
    this._text_26 = this.renderer.createText(this._el_25,'',(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._text_28 = this.renderer.createText(this._el_21,'\n\n      Two-way binding: ',(null as any));
    this._el_29 = import4.createRenderElement(this.renderer,this._el_21,'input',new import4.InlineArray2(2,'type','text'),(null as any));
    this._text_30 = this.renderer.createText(this._el_21,'\n\n      ',(null as any));
    this._el_31 = import4.createRenderElement(this.renderer,this._el_21,'br',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_21,'\n      ',(null as any));
    this._el_33 = import4.createRenderElement(this.renderer,this._el_21,'br',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_34 = this.renderer.createText(this._el_21,'\n\n      ',(null as any));
    this._el_35 = import4.createRenderElement(this.renderer,this._el_21,'strong',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Router-outlet:',(null as any));
    this._text_37 = this.renderer.createText(this._el_21,'\n      ',(null as any));
    this._el_38 = import4.createRenderElement(this.renderer,this._el_21,'main',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n        ',(null as any));
    this._el_40 = import4.createRenderElement(this.renderer,this._el_38,'router-outlet',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_40 = new import3.AppElement(40,38,this,this._el_40);
    this._RouterOutlet_40_5 = new import13.Wrapper_RouterOutlet(this.parentInjector.get(import18.RouterOutletMap),this._appEl_40.vcRef,this.parentInjector.get(import19.ComponentFactoryResolver),(null as any));
    this._text_41 = this.renderer.createText(this._el_38,'\n      ',(null as any));
    this._text_42 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._text_43 = this.renderer.createText(this._el_19,'\n  ',(null as any));
    this._text_44 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_6,'click',this.eventHandler(this._handle_click_6_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_29,'input',this.eventHandler(this._handle_input_29_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.RouterLinkWithHref) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._RouterLinkWithHref_6_3.context; }
    if (((token === import21.RouterLinkActive) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._RouterLinkActive_6_4.context; }
    if (((token === import20.RouterLinkWithHref) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._RouterLinkWithHref_9_3.context; }
    if (((token === import21.RouterLinkActive) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._RouterLinkActive_9_4.context; }
    if (((token === import20.RouterLinkWithHref) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLinkWithHref_12_3.context; }
    if (((token === import21.RouterLinkActive) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLinkActive_12_4.context; }
    if (((token === import20.RouterLinkWithHref) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkWithHref_15_3.context; }
    if (((token === import21.RouterLinkActive) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkActive_15_4.context; }
    if (((token === import0.XLargeDirective) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._XLargeDirective_25_3.context; }
    if (((token === import22.RouterOutlet) && (40 === requestNodeIndex))) { return this._RouterOutlet_40_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_6_0_0:any = 'home';
    this._RouterLinkWithHref_6_3.check_routerLink(currVal_6_0_0,throwOnChange,false);
    this._RouterLinkWithHref_6_3.detectChangesInInputProps(this,this._el_6,throwOnChange);
    const currVal_6_1_0:any = 'router-link-active';
    this._RouterLinkActive_6_4.check_routerLinkActive(currVal_6_1_0,throwOnChange,false);
    this._RouterLinkActive_6_4.detectChangesInInputProps(this,this._el_6,throwOnChange);
    const currVal_9_0_0:any = 'about';
    this._RouterLinkWithHref_9_3.check_routerLink(currVal_9_0_0,throwOnChange,false);
    this._RouterLinkWithHref_9_3.detectChangesInInputProps(this,this._el_9,throwOnChange);
    const currVal_9_1_0:any = 'router-link-active';
    this._RouterLinkActive_9_4.check_routerLinkActive(currVal_9_1_0,throwOnChange,false);
    this._RouterLinkActive_9_4.detectChangesInInputProps(this,this._el_9,throwOnChange);
    const currVal_12_0_0:any = 'todo';
    this._RouterLinkWithHref_12_3.check_routerLink(currVal_12_0_0,throwOnChange,false);
    this._RouterLinkWithHref_12_3.detectChangesInInputProps(this,this._el_12,throwOnChange);
    const currVal_12_1_0:any = 'router-link-active';
    this._RouterLinkActive_12_4.check_routerLinkActive(currVal_12_1_0,throwOnChange,false);
    this._RouterLinkActive_12_4.detectChangesInInputProps(this,this._el_12,throwOnChange);
    const currVal_15_0_0:any = 'lazy';
    this._RouterLinkWithHref_15_3.check_routerLink(currVal_15_0_0,throwOnChange,false);
    this._RouterLinkWithHref_15_3.detectChangesInInputProps(this,this._el_15,throwOnChange);
    const currVal_15_1_0:any = 'router-link-active';
    this._RouterLinkActive_15_4.check_routerLinkActive(currVal_15_1_0,throwOnChange,false);
    this._RouterLinkActive_15_4.detectChangesInInputProps(this,this._el_15,throwOnChange);
    this._XLargeDirective_25_3.detectChangesInInputProps(this,this._el_25,throwOnChange);
    this._RouterOutlet_40_5.detectChangesInInputProps(this,this._el_40,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_6_0.dirty) {
        this._query_RouterLink_6_0.reset(([] as any[]));
        this._RouterLinkActive_6_4.context.links = this._query_RouterLink_6_0;
        this._query_RouterLink_6_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_6_1.dirty) {
        this._query_RouterLinkWithHref_6_1.reset([this._RouterLinkWithHref_6_3.context]);
        this._RouterLinkActive_6_4.context.linksWithHrefs = this._query_RouterLinkWithHref_6_1;
        this._query_RouterLinkWithHref_6_1.notifyOnChanges();
      }
      if (this._query_RouterLink_9_0.dirty) {
        this._query_RouterLink_9_0.reset(([] as any[]));
        this._RouterLinkActive_9_4.context.links = this._query_RouterLink_9_0;
        this._query_RouterLink_9_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_9_1.dirty) {
        this._query_RouterLinkWithHref_9_1.reset([this._RouterLinkWithHref_9_3.context]);
        this._RouterLinkActive_9_4.context.linksWithHrefs = this._query_RouterLinkWithHref_9_1;
        this._query_RouterLinkWithHref_9_1.notifyOnChanges();
      }
      if (this._query_RouterLink_12_0.dirty) {
        this._query_RouterLink_12_0.reset(([] as any[]));
        this._RouterLinkActive_12_4.context.links = this._query_RouterLink_12_0;
        this._query_RouterLink_12_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_12_1.dirty) {
        this._query_RouterLinkWithHref_12_1.reset([this._RouterLinkWithHref_12_3.context]);
        this._RouterLinkActive_12_4.context.linksWithHrefs = this._query_RouterLinkWithHref_12_1;
        this._query_RouterLinkWithHref_12_1.notifyOnChanges();
      }
      if (this._query_RouterLink_15_0.dirty) {
        this._query_RouterLink_15_0.reset(([] as any[]));
        this._RouterLinkActive_15_4.context.links = this._query_RouterLink_15_0;
        this._query_RouterLink_15_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_15_1.dirty) {
        this._query_RouterLinkWithHref_15_1.reset([this._RouterLinkWithHref_15_3.context]);
        this._RouterLinkActive_15_4.context.linksWithHrefs = this._query_RouterLinkWithHref_15_1;
        this._query_RouterLinkWithHref_15_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_6_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_9_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_12_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_15_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_6_3.detectChangesInHostProps(this,this._el_6,throwOnChange);
    this._RouterLinkActive_6_4.detectChangesInHostProps(this,this._el_6,throwOnChange);
    this._RouterLinkWithHref_9_3.detectChangesInHostProps(this,this._el_9,throwOnChange);
    this._RouterLinkActive_9_4.detectChangesInHostProps(this,this._el_9,throwOnChange);
    this._RouterLinkWithHref_12_3.detectChangesInHostProps(this,this._el_12,throwOnChange);
    this._RouterLinkActive_12_4.detectChangesInHostProps(this,this._el_12,throwOnChange);
    this._RouterLinkWithHref_15_3.detectChangesInHostProps(this,this._el_15,throwOnChange);
    this._RouterLinkActive_15_4.detectChangesInHostProps(this,this._el_15,throwOnChange);
    this._XLargeDirective_25_3.detectChangesInHostProps(this,this._el_25,throwOnChange);
    const currVal_64:any = import4.interpolate(1,'Universal JavaScript ',this.context.title,'!');
    if (import4.checkBinding(throwOnChange,this._expr_64,currVal_64)) {
      this.renderer.setText(this._text_26,currVal_64);
      this._expr_64 = currVal_64;
    }
    const currVal_65:any = this.context.title;
    if (import4.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this.renderer.setElementProperty(this._el_29,'value',currVal_65);
      this._expr_65 = currVal_65;
    }
    this._RouterOutlet_40_5.detectChangesInHostProps(this,this._el_40,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_6_3.context.ngOnDestroy();
    this._RouterLinkActive_6_4.context.ngOnDestroy();
    this._RouterLinkWithHref_9_3.context.ngOnDestroy();
    this._RouterLinkActive_9_4.context.ngOnDestroy();
    this._RouterLinkWithHref_12_3.context.ngOnDestroy();
    this._RouterLinkActive_12_4.context.ngOnDestroy();
    this._RouterLinkWithHref_15_3.context.ngOnDestroy();
    this._RouterLinkActive_15_4.context.ngOnDestroy();
    this._RouterOutlet_40_5.context.ngOnDestroy();
  }
  private _handle_click_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_6_0:any = ((<any>this._RouterLinkWithHref_6_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_6_0);
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_9_0:any = ((<any>this._RouterLinkWithHref_9_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_9_0);
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_12_0:any = ((<any>this._RouterLinkWithHref_12_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_12_0);
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_15_0:any = ((<any>this._RouterLinkWithHref_15_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_15_0);
  }
  private _handle_input_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_29_0:any = ((<any>(this.context.title = $event.target.value)) !== false);
    return (true && pd_29_0);
  }
}
export function viewFactory_AppComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}