/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['blockquote[_ngcontent-%COMP%] {\r\n  border-left:5px #158126 solid;\r\n  background:#fff;\r\n  padding:20px 20px 20px 40px;\r\n}\r\nblockquote[_ngcontent-%COMP%]::before {\r\n  left: 1em;\r\n}'];